CREATE TABLE users(
    id BIGINT,
    platform TEXT,
    notify BOOLEAN DEFAULT true,
    format INT DEFAULT 0,
    group_name TEXT,
    query TEXT,
    faculty_ids INT[],
    can_run_mailing BOOLEAN DEFAULT false,
    wants_mailing BOOLEAN DEFAULT true,
    role TEXT,

    PRIMARY KEY(id, platform)
);

CREATE TABLE faculties(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    short_display_name TEXT NOT NULL
);
